application: develomaps
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /templatetags
  static_dir: templatetags

- url: /.*
  script: handlers/main.py